---
title: "STAT 346 Final Project"
author: "Eddy D. Varela, Chenyang Sun, Jackson Bibbens"
date: "4/20/2020"
output: pdf_document
---

```{r}

# top top 10 states: NY, NJ, MA, IL, CA, PA, MI, FL, LA, TX
# change formula for deaths/county pop

library(data.table)
confirmedCasesUS = fread('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv')
confirmedDeathsUS = fread('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv')
hospitalData = read.csv('data/Hospitals.csv', header = TRUE)
mobilityReport = fread('https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv')
stayHomeClean = read.csv('data/StayHomeOrder.csv', header = TRUE)
countyPop = read.csv('data/countyPop.csv', header = TRUE)

head(confirmedCasesUS)
head(confirmedDeathsUS)
head(stayHomeClean)
head(countyPop)
hospitalData

```

Preprocessing data to fix column names and remove columns that we are not going to use:
```{r}
library(tidyverse)

#Confirmed Cases
casesClean = confirmedCasesUS[,-2:-5]
casesClean = casesClean[,-7]
names(casesClean)[names(casesClean) == "Admin2"] <- "County"

#Confirmed Deaths
deathesClean = confirmedDeathsUS[,-2:-5]
deathesClean = deathesClean[,-7]
names(deathesClean)[names(deathesClean) == "Admin2"] <- "County"

#Hospital Data
hospitalClean = hospitalData %>% filter(
  TYPE == "GENERAL ACUTE CARE" | TYPE == "LONG TERM CARE"|
  TYPE == "CRITICAL ACCESS" | TYPE == "CHILDREN")

# we want to anonymize the name of the hospital and remove lat/longitude data, and other id and columns where all the values are the same. We have also removed hospitals that would not be treating people who are infected with the virus.

head(hospitalData)
hospitalClean = hospitalData[,-c(1:6, 10:11, 16, 17, 20, 22:29,31,34)]
hospitalClean
rapply(hospitalData,function(x)length(unique(x)))

types = hospitalData$TYPE[!duplicated(hospitalData$TYPE)]

#Filtering out the regions that are not the United States, each row is a day where the columns represent the %change  from baseline in different categories such as retail, transit, parks, etc...
# When both sub_region_1 and sub_region_2 is empty then we are looking at the whole US
# When sub_region_2 is empty we are looking at the statewide mobility report, I am keeping these in for future use cases.
mobilityReportClean = mobilityReport[which(mobilityReport$country_region=='United States')]


head(casesClean)
head(deathesClean)
head(hospitalClean)
mobilityReportClean
head(stayHomeClean)
```

```{r StayHome}
# Need to translate StayHome date into a category "bucket" 
# Group 1: Orders on/before 3/23
# Group 2: Orders between 3/24 - 3/26
# Group 3: Orders between 3/27 - 3/31
# Group 4: Orders on/after 4/1
stayHomeClean$Start.Date = as.Date(stayHomeClean$Start.Date)

#Creating Dummy Variables for each group
stayHomeClean$start.1 = ifelse(stayHomeClean$Start.Date <= as.Date('2020-03-23'),1,0)
stayHomeClean$start.2 = ifelse(stayHomeClean$Start.Date > as.Date('2020-03-23') & stayHomeClean$Start.Date <= as.Date('2020-03-26') ,1,0)
stayHomeClean$start.3 = ifelse(stayHomeClean$Start.Date > as.Date('2020-03-26') & stayHomeClean$Start.Date <= as.Date('2020-03-31'),1,0)
stayHomeClean$start.4 = ifelse(stayHomeClean$Start.Date >= as.Date('2020-04-01'),1,0)

```

```{r income}
# Adding data set for per capital income 2018 for each county
incomeData = read.csv('data/lapi1119.csv',header = TRUE)
```

```{r countyData}
#Create a unified "countyData" table which will link each county to: 
# mortality rate, total cases, total deaths, # beds, ∆retail, ∆grocery, ∆parks, ∆transit, ∆work, ∆residential, stay at home, income

#Subsetting data for only counties in top 10 states
topStates = c("New York","New Jersey","Massachusetts","Illinois","California","Pennsylvania", "Michigan", "Florida","Louisiana", "Texas")

#Income

incomeDataClean = subset(incomeData, State %in% topStates )
names(incomeDataClean) = c("State","County","Income.2018")

#Cases - only as of 4/26/2020
casesSub = subset(casesClean, (Province_State %in% topStates) & UID <84060000)
casesSub$totalCases = casesSub$"4/26/20"
casesSub = casesSub[,c("County","Province_State","totalCases")]
casesSub = casesSub[,c(2,1,3)]
names(casesSub) = c("State","County","totalCases")

#Deaths - only as of 4/26/2020
deathsSub = subset(deathesClean, (Province_State %in% topStates) & UID <84060000)
deathsSub$totalDeaths = deathsSub$"4/26/20"
deathsSub = deathsSub[,c("County","Province_State","totalDeaths")]
deathsSub = deathsSub[,c(2,1,3)]
names(deathsSub) = c("State","County","totalDeaths")

#Population - 2019 estimates
populationSub = subset(countyPop, STNAME %in% topStates & as.character(STNAME)!=as.character(CTYNAME))
populationSub = populationSub[,c("STNAME","CTYNAME","POPESTIMATE2019")]
names(populationSub) = c("State","County","Pop.2019")
populationSub$County = sub(populationSub$County, pattern = " [[:alpha:]]*$", replacement = "")

#Hospital 
library(tools)
hospitalSub = subset(hospitalClean,STATE %in% c("CA","NY","NJ","MA","LA","TX","MI","IL","FL","PA"))
hospitalSub = hospitalSub[,c("STATE","COUNTY","BEDS")]
hospitalSub = hospitalSub[hospitalSub$BEDS!=-999,]
aggregateBeds = data.frame(aggregate(BEDS~COUNTY+STATE,hospitalSub,sum))
aggregateBeds = aggregateBeds[c(2,1,3)]
aggregateBeds$STATE = as.character(aggregateBeds$STATE )
aggregateBeds$COUNTY = toTitleCase(tolower(as.character(aggregateBeds$COUNTY )))

for (i in 1:nrow(aggregateBeds)){
  if (as.character(aggregateBeds[i,1]) == "CA"){
    aggregateBeds[i,1] = "California"
  }
  if (as.character(aggregateBeds[i,1]) == "NJ"){
    aggregateBeds[i,1] = "New Jersey"
  }
  if (as.character(aggregateBeds[i,1]) == "NY"){
    aggregateBeds[i,1] = "New York"
  }
  if (as.character(aggregateBeds[i,1]) == "MA"){
    aggregateBeds[i,1] = "Massachusetts"
  }
  if (as.character(aggregateBeds[i,1]) == "PA"){
    aggregateBeds[i,1] = "Pennslyvania"
  }
  if (as.character(aggregateBeds[i,1]) == "MI"){
    aggregateBeds[i,1] = "Michigan"
  }
  if (as.character(aggregateBeds[i,1]) == "IL"){
    aggregateBeds[i,1] = "Illinois"
  }
  if (as.character(aggregateBeds[i,1]) == "LA"){
    aggregateBeds[i,1] = "Louisiana"
  }
  if (as.character(aggregateBeds[i,1]) == "FL"){
    aggregateBeds[i,1] = "Florida"
  }
  if (as.character(aggregateBeds[i,1]) == "TX"){
    aggregateBeds[i,1] = "Texas"
  }
}
names(aggregateBeds) = c("State","County","Beds")




countyData = merge(deathsSub,casesSub)
countyData = merge(countyData,incomeData)
countyData = merge(countyData,aggregateBeds)
countyData = merge(countyData,populationSub)
countyData$StayHomeDate = as.character("2020-01-01")
for (i in 1:nrow(countyData)){
  if (countyData[i,1] == "California") {
    countyData$StayHomeDate[i] = "2020-03-19"
  }
  if (countyData[i,1] == "New Jersey") {
    countyData$StayHomeDate[i] = "2020-03-21"
  }
  if (countyData[i,1] == "New York") {
    countyData$StayHomeDate[i] = "2020-03-22"
  }
  if (countyData[i,1] == "Massachusetts") {
    countyData$StayHomeDate[i] = "2020-03-24"
  }
  if (countyData[i,1] == "Illinois") {
    countyData$StayHomeDate[i] = "2020-03-21"
  }
 if (countyData[i,1] == "Pennslyvania") {
    countyData$StayHomeDate[i] = "2020-04-01"
  }
  if (countyData[i,1] == "Michigan") {
    countyData$StayHomeDate[i] = "2020-03-24"
  }
  if (countyData[i,1] == "Florida") {
    countyData$StayHomeDate[i] = "2020-04-03"
  }
  if (countyData[i,1] == "Texas") {
    countyData$StayHomeDate[i] = "2020-04-02"
  }
  if (countyData[i,1] == "Louisiana") {
    countyData$StayHomeDate[i] = "2020-03-23"
  }
}

#Will need to merge the datasets 

```





